# This workflow will publish a package to npm when a release is created.
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# TODO: add tests or leave them out, add build steps...?

name: npm publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      # - run: npm run build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
